# fly.toml app configuration file generated for bobshell on 2026-05-02T21:38:57+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bobshell'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
